config/routes.rb
FilePickerDemo::Application.routes.draw do

  root to: "attachments#index"

  resources :attachments, only: [:index, :new, :create]

end

app/models/attachment.rb
class Attachment < ActiveRecord::Base
  attr_accessible :file_url
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/attachments_controller.rb
class AttachmentsController < ApplicationController

  def new
    @attachment = Attachment.new
  end

  def create
    Attachment.create(params[:attachment])
    redirect_to attachments_url
  end

  def index
    @attachments = Attachment.all
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/attachments/index.html.erb
<%= link_to "New attachment", new_attachment_url %>
<table>
  <tr><th>Id</th><th>Filepicker.io Url</th><th>image</th></tr>

  <% @attachments.each do |a| %>

  <tr><td><%= a.id %></td><td><%= a.file_url %></td>
    <td><%= filepicker_image_tag a.file_url, w: 300, h: 300 %></td>
  <td><%= filepicker_save_button "Download", a.file_url, "image/png" %></tr>

  <% end %>
</table>

app/views/attachments/new.html.erb
<%= form_for @attachment do |f| %>

  <%= f.filepicker_field :file_url, dragdrop: true %>
  <%= f.submit %>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FilePickerDemo</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= filepicker_js_include_tag %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>
</body>
</html>